export default function Privacy() {
    return (
        <main className="max-w-3xl mx-auto py-20 px-6">
            <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
            <p>This website does not store personal content generated by users.</p>
        </main>
    )
}